=== qlik-oss/scriptappy/scripts/partial.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "A JSON Schema for JavaScript API specification",
  "description": "API specification",
  "type": "object",
  "required": [
    "spec",
    "info",
    "entries"
  ],
  "additionalProperties": false,
  "patternProperties": {
    "^x-": {
      "$ref": "#/definitions/vendor"
    }
  },
  "properties": {
    "spec": {
      "type": "object",
      "description": "Info about the specification version the document uses",
      "properties": {
        "version": { "type": "string", "enum": ["0.x"]}
      },
      "required": ["version"],
      "additionalProperties": false
    },
    "info": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "A description of the API"
        },
        "name": {
          "type": "string",
          "description": "Name of the API"
        },
        "version": { "$ref": "#/definitions/version" },
        "license": {
          "type": "string",
          "description": "SPDX license identifier"
        },
        "stability": {
          "$ref": "#/definitions/stability"
        }
      },
      "required": ["name", "version"],
      "additionalProperties": false,
      "patternProperties": {
        "^x-": {
          "$ref": "#/definitions/vendor"
        }
      }
    },
    "entries": {
      "additionalProperties": {
        "type": "object",
        "oneOf": [
          {
            "$ref": "#/definitions/entity-tier0"
          },
          {
            "$ref": "#/definitions/entity-tier1"
          },
          {
            "$ref": "#/definitions/entity-tier2"
          },
          {
            "$ref": "#/definitions/entity-tier3"
          }
        ]
      }
    },
    "definitions": {
      "additionalProperties": {
        "type": "object",
        "oneOf": [
          {
            "$ref": "#/definitions/entity-tier1"
          },
          {
            "$ref": "#/definitions/entity-tier2"
          },
          {
            "$ref": "#/definitions/entity-tier3"
          }
        ]
      }
    }
  },
  "definitions": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+.[0-9]+.[0-9]+$"
    },
    "vendor": {
      "additionalProperties": true,
      "additionalItems": true
    },
    "availability": {
      "type": "object",
      "properties": {
        "since": {
          "description": "API version from which owning entity is available.",
          "$ref": "#/definitions/version"
        },
        "deprecated": {
          "description": "Current deprecation status of owning entity.",
          "oneOf": [
            { "type": "boolean" },
            { "$ref": "#/definitions/deprecated" }
          ]
        }
      },
      "additionalProperties": false,
      "examples": ["\n  \"since\": \"1.0.0\",\n  \"deprecated\": false\n"]
    },
    "deprecated": {
      "type": "object",
      "properties": {
        "since": {
          "description": "API version from which owning entity is considered deprecated.",
          "$ref": "#/definitions/version"
        },
        "description": {
          "description": "A short description and a recommendation on what to use instead of the deprecated entity.",
          "type": "string"
        }
      },
      "required": ["since"],
      "additionalProperties": false,
      "examples": ["\n  \"since\": \"1.4.5\",\n  \"description\": \"Deprecated since 1.4.5, use something else instead :P.\"\n"]
    },
    "stability": {
      "description": "Stability of the entity",
      "type": "string",
      "enum": ["experimental", "stable", "locked"]
    }
  }
}

=== qlik-oss/scriptappy/packages/jsdoc2spec/examples/nodejs/spec.json
{
  "spec": {
    "version": "0.x"
  },
  "info": {
    "name": "nodejs",
    "version": "8.0.0"
  },
  "entries": {
    "module:net": {
      "stability": "stable",
      "kind": "module",
      "entries": {
        "Server": {
          "description": "This class is used to create a TCP or ICP server",
          "kind": "class",
          "constructor": {
            "params": []
          },
          "entries": {
            "address": {
              "description": "Returns the bound address.",
              "kind": "function",
              "params": [],
              "returns": {
                "type": "#/entries/module:net/entries/Server/definitions/address"
              }
            },
            "close": {
              "description": "Stops the server from accepting new connections and keeps existing connections",
              "kind": "function",
              "params": []
            },
            "connections": {
              "description": "The number of concurrent connections on the server.",
              "availability": {
                "since": "0.2.0",
                "deprecated": {
                  "description": "since 0.9.7. Use {@link module:net.Server#getConnection()} instead",
                  "since": "0.9.7"
                }
              },
              "type": "any"
            },
            "getConnections": {
              "availability": {
                "since": "0.9.7"
              },
              "kind": "function",
              "params": [
                {
                  "name": "callback",
                  "type": "function"
                }
              ],
              "returns": {
                "type": "#/entries/module:net/entries/Server"
              }
            }
          },
          "definitions": {
            "address": {
              "kind": "object",
              "entries": {
                "port": {
                  "type": "number"
                },
                "family": {
                  "type": "string"
                },
                "address": {
                  "type": "string"
                }
              }
            }
          },
          "events": {
            "close": {
              "description": "Emitted when the server closes",
              "kind": "event",
              "params": []
            },
            "connect": {
              "description": "Emitted when a new connection is made.",
              "kind": "event",
              "params": [
                {
                  "name": "socket",
                  "description": "The connection object",
                  "type": "module:net.Socket"
                }
              ]
            }
          }
        },
        "createServer": {
          "description": "Creates a new TCP or ICP server.",
          "kind": "function",
          "params": [
            {
              "name": "options",
              "optional": true,
              "kind": "object",
              "entries": {
                "allowHalfOpen": {
                  "description": "Indicates whether half-opened TCP connections are allowed.",
                  "optional": true,
                  "defaultValue": false,
                  "type": "boolean"
                },
                "pauseOnConnect": {
                  "description": "Indicates whether the socket should be paused on incoming connections.",
                  "optional": true,
                  "defaultValue": false,
                  "type": "boolean"
                }
              }
            },
            {
              "name": "connectionsListener",
              "description": "Automatically sets a listener for the `connection` event.",
              "optional": true,
              "type": "function"
            }
          ],
          "returns": {
            "type": "#/entries/module:net/entries/Server"
          }
        }
      }
    },
    "module:path": {
      "stability": "stable",
      "kind": "module",
      "entries": {
        "dirname": {
          "description": "Returns the directory name of a `path`",
          "kind": "function",
          "params": [
            {
              "name": "path",
              "type": "string"
            }
          ],
          "returns": {
            "type": "string"
          }
        },
        "extname": {
          "description": "Returns the extension of the `path`",
          "kind": "function",
          "params": [
            {
              "name": "path",
              "type": "string"
            }
          ],
          "returns": {
            "type": "string"
          }
        },
        "win32": {
          "description": "Provides acces to Window-specific implementations of the `path` methods",
          "kind": "object",
          "entries": {}
        }
      }
    }
  },
  "definitions": {}
}
